# Generated by Django 5.2.8 on 2025-11-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('difficulty', models.IntegerField(help_text='1=low, 2=medium, 3=high')),
                ('importance', models.IntegerField(help_text='1=low, 2=medium, 3=high')),
                ('estimated_time', models.IntegerField(help_text='time in hours')),
                ('priority_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
